name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['26.0.1']
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Run setup
      run: make setup
    - name: Run lint
      run: make lint
    - name: Run build
      run: make clean build
    - name: Run tests
      run: make test
